services:
  - type: web
    name: entry_project
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate --noinput && gunicorn entryproject.wsgi
    envVars:
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        value: "postgresql://postgres:135720entry@db.zryxbvtlfdigbsalhtpt.supabase.co:5432/postgres"
