# Generated by Django 5.1.7 on 2025-04-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entryapp', '0002_invitationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryexitrecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
