# Generated by Django 5.1.7 on 2025-04-04 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entryapp', '0003_alter_entryexitrecord_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryexitrecord',
            name='entry_count',
        ),
        migrations.RemoveField(
            model_name='entryexitrecord',
            name='exit_count',
        ),
    ]
