# Generated by Django 5.1.7 on 2025-04-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entryapp', '0004_remove_entryexitrecord_entry_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
