# Generated by Django 5.1.7 on 2025-04-12 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entryapp', '0006_rename_date_entryexitrecord_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_shops', models.BooleanField(default=False, verbose_name='Mağaza Yönetimi')),
                ('can_manage_devices', models.BooleanField(default=False, verbose_name='Cihaz Yönetimi')),
                ('can_view_statistics', models.BooleanField(default=True, verbose_name='İstatistikleri Görüntüleme')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Kullanıcı Yönetimi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı İzni',
                'verbose_name_plural': 'Kullanıcı İzinleri',
            },
        ),
    ]
