# Generated by Django 5.1.7 on 2025-04-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entryapp', '0008_entryexitrecord_is_exit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='shop_id',
            new_name='customer_id',
        ),
        migrations.AddField(
            model_name='shop',
            name='customer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
