# Generated by Django 5.2 on 2025-10-20 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entryapp', '0010_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entryexitrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='entryexitrecord',
            name='rssi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entryexitrecord',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='entryexitrecord',
            name='device',
            field=models.ForeignKey(default=1995, on_delete=django.db.models.deletion.CASCADE, to='entryapp.device'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entryexitrecord',
            name='is_entry',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='entryexitrecord',
            name='is_exit',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='entryexitrecord',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entryapp.shop'),
        ),
    ]
