# Generated by Django 5.2 on 2025-10-20 21:49

import django.db.models.deletion
from django.db import migrations, models
from django.core.exceptions import FieldDoesNotExist
from django.db import connection

def add_rssi_field_if_not_exists(apps, schema_editor):
    # Check if the field already exists
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='entryapp_entryexitrecord' AND column_name='rssi'
        """)
        if not cursor.fetchone():
            # Field doesn't exist, add it
            cursor.execute("ALTER TABLE entryapp_entryexitrecord ADD COLUMN rssi integer NULL")


def reverse_add_rssi_field(apps, schema_editor):
    # Check if the field exists before dropping
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='entryapp_entryexitrecord' AND column_name='rssi'
        """)
        if cursor.fetchone():
            # Field exists, drop it
            cursor.execute("ALTER TABLE entryapp_entryexitrecord DROP COLUMN rssi")



class Migration(migrations.Migration):

    dependencies = [
        ('entryapp', '0010_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entryexitrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.RunPython(add_rssi_field_if_not_exists, reverse_code=reverse_add_rssi_field),
        migrations.AlterField(
            model_name='entryexitrecord',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='entryexitrecord',
            name='device',
            field=models.ForeignKey(default=1995, on_delete=django.db.models.deletion.CASCADE, to='entryapp.device'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entryexitrecord',
            name='is_entry',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='entryexitrecord',
            name='is_exit',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='entryexitrecord',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entryapp.shop'),
        ),
    ]