# Generated by Django 5.2 on 2025-10-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entryapp', '0012_role_userrole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='customer_id',
            new_name='shop_id',
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_manage_devices',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_manage_shops',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_manage_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_view_statistics',
            field=models.BooleanField(default=True),
        ),
    ]
