# Generated by Django 5.2 on 2025-10-22 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entryapp', '0014_goal_dailyentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_goals', to=settings.AUTH_USER_MODEL),
        ),
    ]
