# Generated by Django 5.1.7 on 2026-05-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entryapp', '0016_device_current_version_and_devicestatuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='notification_push_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='notification_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
