# Generated by Django 5.1.7 on 2026-05-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entryapp', '0017_entryexitrecord_rssi_shop_notification_push_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='notification_time',
        ),
        migrations.AddField(
            model_name='shop',
            name='notification_end_time',
            field=models.TimeField(blank=True, help_text='Bildirim bitiş saati', null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='notification_start_time',
            field=models.TimeField(blank=True, help_text='Bildirim başlangıç saati', null=True),
        ),
    ]
